# Generated by Django 5.0.6 on 2025-02-04 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myDabra', '0002_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
